{
 "title": "Gaming Overview",
 "description": "Visualizes Gaming Platform metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "APCu Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "app_apcu_memory_available", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(app_http_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "p50 By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method, route) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "p75 By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (le, method, route) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "p95 By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method, route) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "p99 By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, route) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "Status Codes Last 5 Minutes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (increase(app_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last 30 Minutes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (increase(app_http_requests_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (increase(app_http_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(class) (rate(app_http_exceptions_total[$__rate_interval]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Exceptions Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by(class) (rate(app_http_exceptions_total[1h]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Exceptions / s By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(app_http_exceptions_total[$__rate_interval]))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "Exceptions Last Hour By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(app_http_exceptions_total[1h]))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Queries / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(sql) (rate(app_sql_query_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "p50 By Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, sql) (rate(app_sql_query_duration_seconds_bucket[5m])))",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "p75 By Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (le, sql) (rate(app_sql_query_duration_seconds_bucket[5m])))",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "p95 By Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, sql) (rate(app_sql_query_duration_seconds_bucket[5m])))",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  {
   "title": "p99 By Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, sql) (rate(app_sql_query_duration_seconds_bucket[5m])))",
     "legendFormat": "{{sql}}"
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Messages / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(app_messaging_messages_total[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "p50 By Message In Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, topic, message) (rate(app_messaging_message_duration_seconds_bucket[5m])))",
     "legendFormat": "{{topic}} - {{message}}"
    }
   ]
  },
  {
   "title": "p75 By Message In Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (le, topic, message) (rate(app_messaging_message_duration_seconds_bucket[5m])))",
     "legendFormat": "{{topic}} - {{message}}"
    }
   ]
  },
  {
   "title": "p95 By Message In Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, topic, message) (rate(app_messaging_message_duration_seconds_bucket[5m])))",
     "legendFormat": "{{topic}} - {{message}}"
    }
   ]
  },
  {
   "title": "p99 By Message In Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, topic, message) (rate(app_messaging_message_duration_seconds_bucket[5m])))",
     "legendFormat": "{{topic}} - {{message}}"
    }
   ]
  },
  { "title": "Event Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Commits / s By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "sum by(job) (rate(app_event_store_commits_total[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Lag By Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "app_event_store_lag_seconds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}