{
 "title": "Nchan Overview",
 "description": "Visualizes Nchan metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nchan_channels{job=\"nchan\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Messages / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nchan_total_published_messages{job=\"nchan\", instance=\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nchan_shared_memory_used{job=\"nchan\", instance=\"$instance\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stored Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "nchan_stored_messages{job=\"nchan\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "nchan_subscribers{job=\"nchan\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "nchan_channels{job=\"nchan\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}