{
 "title": "Traefik Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(traefik_service_requests_total, instance)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\"}[1h])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "service" },
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{service=\"$service\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{service=\"$service\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{service=\"$service\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traefik_service_request_duration_seconds_bucket{service=\"$service\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_bytes_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_responses_bytes_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Status Codes Last 5 Minutes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "repeat": "services",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[5m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last 30 Minutes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[30m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[1h])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}